Description: Andre Gregorio - Udacity Devops Nanodegree - Project 02

Parameters:
  EnvironmentName:
    Description: The environment name for the project.
    Type: String
    Default: UdacityDevops-P02

Resources:
  Ec2DefaultRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DefaultApplicationServer
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} default EC2 IAM Role

  Ec2DefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:List*
            Resource: "*"
      PolicyName: Ec2DefaultPolicy
      Roles:
        - Ref: Ec2DefaultRole

  Ec2DefaultProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: Ec2DefaultRole
      Path: "/"

  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP on port 80 and SSH on port 22
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  WebAppLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData: # Change to whatever s3 bucket the code is hosted at
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install unzip awscli -y
          apt-get install apache2 -y
          systemctl start apache2.service
          cd /var/www/html
          aws s3 cp s3://udagram-project/index.html .
          chown -R www-data:www-data .
      ImageId: ami-0a634ae95e11c6f91
      IamInstanceProfile: !Ref Ec2DefaultProfile
      InstanceType: t3.medium
      KeyName: aws-ec2-default
      SecurityGroups:
        - Ref: WebAppSecurityGroup
      BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            VolumeSize: 10
